"""agregar_estado_convocatoria_y_notas

Revision ID: c651f7ec08de
Revises: 9733f9599c89
Create Date: 2025-11-18 00:24:34.601904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c651f7ec08de'
down_revision: Union[str, Sequence[str], None] = '9733f9599c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_licitacion', sa.Column('estado_convocatoria', sa.Integer(), nullable=True))
    op.add_column('ca_seguimiento', sa.Column('notas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_seguimiento', 'notas')
    op.drop_column('ca_licitacion', 'estado_convocatoria')
    # ### end Alembic commands ###
